export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_FEATURES = 'SET_FEATURES';
export const ADD_FEATURE = 'ADD_FEAUTRE';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const DELETE_FEATURE = 'DELETE_FEATURE';
