export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_USER_NAME = 'SET_USER_NAME';

export const SET_FEATURES = 'SET_FEATURES';
export const LOADING_FEATURES = 'LOADING_FEATURES';
export const LOAD_FEATURE_ERROR = 'LOAD_FEATURE_ERROR';
export const ADD_FEATURE = 'ADD_FEATURE';
export const ADDING_FEATURE = 'ADDING_FEATURE';
export const ADD_FEATURE_ERROR = 'ADD_FEATURE_ERROR';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const UPDATING_FEATURE = 'UPDATING_FEATURE';
export const UPDATE_FEATURE_ERROR = 'UPDATE_FEATURE_ERROR';
export const DELETE_FEATURE = 'DELETE_FEATURE';
export const DELETING_FEATURE = 'DELETING_FEATURE';
export const DELETE_FEATURE_ERROR = 'DELETE_FEATURE_ERROR';
// saga action
export const INVOKE_LOAD_FEATURE = 'INVOKE_LOAD_FEATURE';

export const SET_SPRINTS = 'SET_SPRINTS';
export const ADD_SPRINT = 'ADD_SPRINT';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const LOADING_SPRINTS = 'LOADING_SPRINTS';
export const LOAD_SPRINT_ERROR = 'LOAD_SPRINT_ERROR';
export const UPDATE_SPRINT_ITEM_STATUS = 'UPDATE_SPRINT_ITEM_STATUS';

export const SHOW_CLOSE_TO_UPDATE = 'SHOW_CLOSE_TO_UPDATE';
