export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_USER_NAME = 'SET_USER_NAME';

export const SET_FEATURES = 'SET_FEATURES';
export const ADD_FEATURE = 'ADD_FEATURE';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const DELETE_FEATURE = 'DELETE_FEATURE';
export const LOADING_FEATURE = 'LOADING_FEATURE';
export const LOAD_FEATURE_ERROR = 'LOAD_FEATURE_ERROR';

export const SET_SPRINTS = 'SET_SPRINTS';
export const ADD_SPRINT = 'ADD_SPRINT';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const LOADING_SPRINT = 'LOADING_SPRINT';
export const LOAD_SPRINT_ERROR = 'LOAD_SPRINT_ERROR';
