export enum ActionKeys {
  SET_LOGIN_STATUS = 'SET_LOGIN_STATUS',
  SET_USER_NAME = 'SET_USER_NAME',

  SET_FEATURES = 'SET_FEATURES',
  ADD_FEATURE = 'ADD_FEATURE',
  UPDATE_FEATURE = 'UPDATE_FEATURE',
  DELETE_FEATURE = 'DELETE_FEATURE',

  SET_SPRINTS = 'SET_SPRINTS',
  ADD_SPRINT = 'ADD_SPRINT',
  UPDATE_SPRINT = 'UPDATE_SPRINT',
  DELETE_SPRINT = 'DELETE_SPRINT'
}
